"""Generate and commit TEAM_STYLE.md from ReviewMind feedback."""

from __future__ import annotations

import logging
from datetime import date

from github import Github, GithubException
from openai import OpenAI

from reviewmind.config import (
    GITHUB_TOKEN,
    MIN_FEEDBACK_FOR_STYLE,
    MODEL,
    OPENAI_API_KEY,
    STYLE_FILE_NAME,
)
from reviewmind.db import (
    get_acceptance_rate,
    get_accepted_patterns,
    get_feedback_count,
    get_rejected_patterns,
    save_style_snapshot,
)


logger = logging.getLogger(__name__)


def _fallback_style_body(accepted: list[str], rejected: list[str]) -> str:
    """Build a demo-safe style body when OpenAI is unavailable."""
    accepted_items = accepted[:4] or ["Prefer specific, actionable review feedback."]
    rejected_items = rejected[:4] or ["Avoid generic comments that do not change code."]
    return "\n".join(
        [
            "## What we care about",
            *(f"- {item}" for item in accepted_items),
            "",
            "## What we ignore",
            *(f"- {item}" for item in rejected_items),
            "",
            "## Naming conventions",
            "- Prefer descriptive names over single-letter variables.",
            "",
            "## Error handling",
            "- Handle external API and database failures explicitly.",
        ]
    )


def build_style_markdown(
    repo_name: str,
    accepted: list[str],
    rejected: list[str],
    rate: float,
    count: int,
) -> str:
    """Generate the full TEAM_STYLE.md markdown content."""
    body = ""
    try:
        if OPENAI_API_KEY and OPENAI_API_KEY.lower() != "mock":
            client = OpenAI(api_key=OPENAI_API_KEY)
            response = client.chat.completions.create(
                model=MODEL,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a technical writer creating a concise coding "
                            "style guide from real team data."
                        ),
                    },
                    {
                        "role": "user",
                        "content": f"""A code review bot collected feedback from a software team. Write TEAM_STYLE.md (max 300 words).

Accepted patterns (team liked these):
{chr(10).join(accepted)}

Rejected patterns (team disliked these):
{chr(10).join(rejected)}

Use these exact markdown sections:
## What we care about
## What we ignore
## Naming conventions
## Error handling

Be specific and direct. Use bullet points.
Current acceptance rate: {rate:.0%}""",
                    },
                ],
            )
            body = response.choices[0].message.content or ""
    except Exception:
        logger.exception("Failed to generate TEAM_STYLE.md with OpenAI for %s", repo_name)

    if not body:
        body = _fallback_style_body(accepted, rejected)

    return f"""# Team Style Guide

> Auto-generated by ReviewMind on {date.today().isoformat()}
> Based on {count} code review feedbacks
> Acceptance rate: {rate:.0%}

---

{body.strip()}
"""


def check_and_generate_style(repo_name: str, github_token: str) -> None:
    """Generate and commit TEAM_STYLE.md when enough feedback exists."""
    try:
        count = get_feedback_count(repo_name)
        if count < MIN_FEEDBACK_FOR_STYLE:
            logger.info("Waiting for more feedback: %s/20", count)
            return None

        accepted = get_accepted_patterns(repo_name, limit=15)
        rejected = get_rejected_patterns(repo_name, limit=8)
        rate = get_acceptance_rate(repo_name)
        style_md = build_style_markdown(repo_name, accepted, rejected, rate, count)

        token = github_token or GITHUB_TOKEN
        if not token:
            save_style_snapshot(repo_name, style_md, rate)
            logger.info("TEAM_STYLE.md generated locally for %s", repo_name)
            return None

        try:
            g = Github(token)
            repo = g.get_repo(repo_name)
            message = (
                f"docs: update TEAM_STYLE.md via ReviewMind "
                f"({rate:.0%} acceptance rate, {count} feedbacks)"
            )
            try:
                existing = repo.get_contents(STYLE_FILE_NAME)
                if isinstance(existing, list):
                    logger.error("%s resolved to a directory", STYLE_FILE_NAME)
                    return None
                repo.update_file(
                    path=STYLE_FILE_NAME,
                    message=message,
                    content=style_md,
                    sha=existing.sha,
                )
            except GithubException as exc:
                if exc.status == 404:
                    repo.create_file(
                        path=STYLE_FILE_NAME,
                        message=message,
                        content=style_md,
                    )
                else:
                    raise
        except Exception:
            logger.exception("Failed to commit TEAM_STYLE.md for %s", repo_name)
            save_style_snapshot(repo_name, style_md, rate)
            return None

        save_style_snapshot(repo_name, style_md, rate)
        logger.info("TEAM_STYLE.md committed for %s", repo_name)
    except Exception:
        logger.exception("Failed to check and generate style for %s", repo_name)
    return None
